name: Build Arduino code

on:
  workflow_dispatch:

jobs:
  
  mainJob:
    runs-on: ubuntu-latest
    
    steps:     
      - name: Checkout
        uses: actions/checkout@v2      
      - name: Build
        uses: arduino/compile-sketches@v1.0.0
        with:
          fqbn: 'arduino:avr:uno'
          libraries: |
            - name: NmraDcc
          sketch-paths: |
            - Arduino
