name: Build Arduino code

on:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: arduino/compile-sketches@v1.0.0
        with:
          fqbn: 'arduino:avr:uno'
          libraries: |
            - name: NmraDcc
          sketch-paths: |
            - Arduino
